### ISSUE TITLE
Jared

### ISSUE THREAD

**Issue by jaredsb** [unicorns-r-us/template-repo#11]
```[tasklist]
### Tasks
- [ ] https://github.com/unicorns-r-us/template-repo/issues/12
- [ ] https://github.com/unicorns-r-us/template-repo/issues/13
- [ ] https://github.com/unicorns-r-us/template-repo/issues/14
```
